Todo_List/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as base_login_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    # path("login/", base_login_views.LoginView.as_view(), name="login"),
    # path("logout/", base_login_views.LogoutView.as_view(), name="logout"),
    path("", include("to_do_list.urls", namespace="to_do_list")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

to_do_list/urls.py
from django.urls import path

from to_do_list.views import (
    TaskListView, TagListView,
    TaskCreateView, TaskUpdateView, TaskDeleteView,
    TagCreateView, TagUpdateView, TagDeleteView,
    change_task_status,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "task/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "task/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete"
    ),
    path(
        "task-apply/<int:pk>/",
        change_task_status,
        name="change-status"
    )
]

app_name = "to_do_list"

to_do_list/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Person(AbstractUser):

    class Meta:
        ordering = ["username"]


class Task(models.Model):
    description = models.TextField(default="Add the task description!")
    created_time = models.DateTimeField(auto_now_add=True)
    deadline = models.DateField(default="2000-01-01")
    is_completed = models.BooleanField()
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="task",
    )
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["is_completed", "deadline"]

to_do_list/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from to_do_list.models import Task, Tag


def change_task_status(request, pk):
    if request.POST:
        profil = get_object_or_404(Task, id=pk)
        if profil.is_completed:
            profil.is_completed = False
        else:
            profil.is_completed = True
        profil.save(update_fields=["is_completed"])
    return redirect('to_do_list:task-list')


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags")
    success_url = reverse_lazy("to_do_list:task-list")
    context_object_name = "task_list"
    paginate_by = 5
    # login_url = '/login/'


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("to_do_list:task-list")
    template_name = "to_do_list/task_form.html"


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("to_do_list:task-list")
    template_name = "to_do_list/task_form.html"


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    template_name = "to_do_list/task_confirm_delete.html"
    success_url = reverse_lazy("to_do_list:task-list")


class TagListView(LoginRequiredMixin, generic.ListView):
    model = Tag
    success_url = reverse_lazy("to_do_list:tag-list")


class TagCreateView(LoginRequiredMixin, generic.CreateView):
    model = Tag
    fields = "__all__"
    template_name = "to_do_list/tag_form.html"
    success_url = reverse_lazy("to_do_list:tag-list")


class TagUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Tag
    fields = "__all__"
    template_name = "to_do_list/tag_form.html"
    success_url = reverse_lazy("to_do_list:tag-list")


class TagDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Tag
    template_name = "to_do_list/tag_confirm_delete.html"
    success_url = reverse_lazy("to_do_list:tag-list")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

{% block title %}
  <title>TODO List</title>
{% endblock %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>

<body>

<div class="main">


  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3">

        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}

      </div>
      <div class="col-sm-9">

        {% block content %}{% endblock %}
        {% include "includes/pagination.html" %}
        {% block pagination %}

        {% endblock %}
      </div>
    </div>
  </div>
</div>

<div class="footer">
  {% block footer %}

  {% endblock %}
</div>

</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }} " class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav">

  {% if user.is_authenticated %}

    <li>User: {{ user.username }}</li>

    <li>
      <a class="btn btn-danger" href="{% url 'logout' %}">Logout</a>
    </li>
    <br>

    <li>
      <a class="sidebar-button"
         href="{% url "to_do_list:task-list" %}">
        Home
      </a>
    </li>
    <br>

    <li>
      <a class="sidebar-button"
         href="{% url "to_do_list:tag-list" %}">
        Tags
      </a>
    </li>

  {% else %}
     <a class="login btn btn-success" href="{% url 'login' %}">Login</a>

  {% endif %}

</ul>

templates/to_do_list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete Task</h1>

  <p>Are you sure you want to delete Tag <strong>"{{ tag.name }}"</strong>?</p>

  <form action="" method="POST">
    {% csrf_token %}

    <input type="submit" class="btn btn-danger" value="Yes, delete"/>

  </form>


{% endblock %}

templates/to_do_list/tag_form.html
{% extends "base.html" %}

{% block content %}

  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit">
  </form>

{% endblock %}

templates/to_do_list/tag_list.html
{% extends "base.html" %}

{% block content %}

  <h1>
    Tags
    <a
        href="{% url 'to_do_list:tag-create' %}"
        style="float: right"
        class="btn btn-primary"
    >
      Add tag
    </a>
  </h1>

  {% if tag_list %}

    <table class="table">

      <thead class="thead-dark">
      <tr class="text-center">
        <th scope="col">Name</th>
        <th scope="col">Update tag</th>
        <th scope="col">Delete tag</th>
      </tr>
      </thead>

      <tbody>
      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td class="text-center">
            <a class="btn btn-secondary" href="{% url 'to_do_list:tag-update' pk=tag.id %}">
              Update
            </a>
          </td>
          <td class="text-center">
            <a class="btn btn-secondary" href="{% url 'to_do_list:tag-delete' pk=tag.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
      </tbody>

    </table>

  {% else %}
    <h3>There are no Tags in TODO List!</h3>
  {% endif %}

{% endblock %}

templates/to_do_list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete Task</h1>

  <p>Are you sure you want to delete Task <strong>"{{ task.description }}"</strong>?</p>

  <form action="" method="POST">
    {% csrf_token %}

    <input type="submit" class="btn btn-danger" value="Yes, delete"/>

  </form>

{% endblock %}

templates/to_do_list/task_form.html
{% extends "base.html" %}

{% block content %}

  <h1>{{ object|yesno:"Update,Create" }} Task</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit">
  </form>

{% endblock %}

templates/to_do_list/task_list.html
{% extends "base.html" %}

{% block content %}

  <h1>
    TODO List
    <a
        href="{% url 'to_do_list:task-create' %}"
        style="float: right"
        class="btn btn-primary"
    >
      Add task
    </a>
  </h1>

  {% if object_list %}

    <table class="table">

      <thead class="thead-dark">
      <tr class="text-center">
        <th scope="col">Content & date of creation</th>
        <th scope="col">Tag</th>
        <th scope="col">Complete Plan Date</th>
        <th scope="col">Completion Mark</th>
        <th scope="col">Upd task</th>
        <th scope="col">Del task</th>
      </tr>
      </thead>

      <tbody>
      {% for task in task_list.all %}
        <tr>
          <td>
            <p>
            <h6>{{ task.description }}</h6>
            </p>
            <p>{{ task.created_time }}</p>
          </td>
          <td>
            {% for tag in task.tags.all %}
              <p>{{ tag.name }}</p>
            {% endfor %}
          </td>
          <td class="text-center">{{ task.deadline }}</td>
          <td class="text-center">
            {% if task.is_completed %}
              <p>
              <form method="POST" action="{% url 'to_do_list:change-status' pk=task.id %}">
                {% csrf_token %}
                <button class="btn btn-success" name="dobtn">Undo</button>
              </form>
              </p>
            {% else %}
              <p>
              <form method="POST" action="{% url 'to_do_list:change-status' pk=task.id %}">
                {% csrf_token %}
                <button class="btn btn-info" name="dobtn">Complete</button>
              </form>
              </p>
            {% endif %}
          </td>
          <td class="text-center">
            <a href="{% url "to_do_list:task-update" pk=task.id %}">
              🆗
            </a>
          </td>
          <td class="text-center">
            <a href="{% url "to_do_list:task-delete" pk=task.id %}">
              ⛔️
            </a>
          </td>
        </tr>
      {% endfor %}
      </tbody>

    </table>

  {% else %}
    <h3>There no Tasks in TODO List</h3>
  {% endif %}

{% endblock %}